# Generated by Django 5.1.15 on 2026-09-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('publish_candidate', models.BooleanField(default=True)),
                ('count_as_candidate', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'candidate statuses',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('election_date', models.DateField(blank=True, null=True)),
                ('petition_open_date', models.DateField(blank=True, null=True)),
                ('petition_close_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='MapColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('mastodon_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ANC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(max_length=4)),
                ('redistricting_year', models.PositiveSmallIntegerField()),
                ('dc_oanc_link', models.URLField(blank=True)),
                ('anc_homepage_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ANC',
                'verbose_name_plural': 'ANCs',
                'ordering': ['redistricting_year', 'designator'],
                'constraints': [models.UniqueConstraint(fields=('designator', 'redistricting_year'), name='unique_anc_per_cycle')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(max_length=8)),
                ('redistricting_year', models.PositiveSmallIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('landmarks', models.TextField(blank=True)),
                ('anc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='directory.anc')),
                ('neighbors', models.ManyToManyField(blank=True, to='directory.district')),
                ('map_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='directory.mapcolor')),
            ],
            options={
                'verbose_name': 'district',
                'ordering': ['redistricting_year', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcboe_status', models.CharField(blank=True, max_length=50)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('write_in_winner_dcboe', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('source_description', models.TextField(blank=True)),
                ('source_link', models.URLField(blank=True)),
                ('dcboe_source_link', models.URLField(blank=True)),
                ('dcboe_updated_at', models.DateField(blank=True, null=True)),
                ('manual_status_source', models.CharField(blank=True, max_length=200)),
                ('manual_status_source_link', models.URLField(blank=True)),
                ('manual_status_updated_at', models.DateField(blank=True, null=True)),
                ('content_updated_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='directory.candidatestatus')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='directory.district')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='directory.election')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='directory.person')),
            ],
            options={
                'ordering': ['election__year', 'district__designator'],
            },
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name_raw', models.CharField(blank=True, max_length=200)),
                ('votes', models.PositiveIntegerField()),
                ('ranking', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('is_write_in_winner', models.BooleanField(default=False)),
                ('margin_of_victory', models.IntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='directory.candidate')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='directory.district')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='directory.election')),
            ],
            options={
                'ordering': ['election__year', 'district__designator', 'ranking'],
            },
        ),
        migrations.CreateModel(
            name='CommissionerTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_date_is_approximate', models.BooleanField(default=False)),
                ('confirmed_not_running', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioner_terms', to='directory.district')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioner_terms', to='directory.person')),
            ],
            options={
                'ordering': ['district__designator', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.PositiveSmallIntegerField()),
                ('redistricting_year', models.PositiveSmallIntegerField()),
                ('councilmember', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['redistricting_year', 'ward_number'],
                'constraints': [models.UniqueConstraint(fields=('ward_number', 'redistricting_year'), name='unique_ward_per_cycle')],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='directory.ward'),
        ),
        migrations.CreateModel(
            name='WriteInWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name_raw', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_in_winners', to='directory.district')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_in_winners', to='directory.election')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_in_wins', to='directory.person')),
            ],
        ),
        migrations.CreateModel(
            name='ANCOverlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_percentage', models.FloatField()),
                ('from_anc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_from', to='directory.anc')),
                ('to_anc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_to', to='directory.anc')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_anc', 'to_anc'), name='unique_anc_overlap')],
            },
        ),
        migrations.CreateModel(
            name='DistrictOverlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_percentage', models.FloatField()),
                ('from_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_from', to='directory.district')),
                ('to_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_to', to='directory.district')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_district', 'to_district'), name='unique_district_overlap')],
            },
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('election', 'person'), name='unique_candidate_per_election'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('designator', 'redistricting_year'), name='unique_district_per_cycle'),
        ),
    ]
