# Generated by Django 5.1.15 on 2026-09-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body', models.TextField(help_text='HTML is allowed (links, paragraphs, etc).')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
