# Generated by Django 5.1.15 on 2026-09-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_historicalcandidate_historicalcommissionerterm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteupdate',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
