# Generated by Django 5.1.15 on 2026-09-27 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_historicalsiteupdate_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_label', models.CharField(blank=True, max_length=200)),
                ('default_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='directory.candidatestatus')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='directory.election')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=200)),
                ('raw_district_designator', models.CharField(blank=True, max_length=8)),
                ('match_candidates_json', models.JSONField(blank=True, default=list)),
                ('best_match_score', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('link', 'Link to existing'), ('new', 'Create new'), ('skip', 'Skip')], default='pending', max_length=10)),
                ('applied', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='directory.personimportbatch')),
                ('chosen_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.person')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.district')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
