# Generated by Django 5.1.15 on 2026-09-28 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_personimportbatch_personimportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='resulting_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.district'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='resulting_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.person'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('general', 'General edit / suggestion (free text)'), ('new_candidate', 'New candidate declared'), ('candidate_withdraws', 'Candidate withdraws'), ('commissioner_change', 'Commissioner stops serving early'), ('new_commissioner', 'New commissioner appointed')], default='general', max_length=30),
        ),
    ]
