# Generated by Django 5.1.15 on 2026-09-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_suggestion_applied_at_suggestion_resulting_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionerterm',
            name='confirmed_not_running',
        ),
        migrations.RemoveField(
            model_name='historicalcommissionerterm',
            name='confirmed_not_running',
        ),
    ]
