# Generated by Django 5.1.15 on 2026-09-29 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_remove_commissionerterm_confirmed_not_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.candidate'),
        ),
    ]
