# Generated by Django 5.1.15 on 2026-09-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_suggestion_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('general', 'General edit / suggestion (free text)'), ('new_candidate', 'New candidate declared'), ('candidate_withdraws', 'Candidate withdrew'), ('commissioner_change', 'Commissioner resigned'), ('new_commissioner', 'New commissioner appointed')], default='general', max_length=30),
        ),
    ]
