# Generated by Django 5.2.17 on 2026-10-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_remove_person_link_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personlink',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='historicalpersonlink',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personlink',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalpersonlink',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
    ]
